TITLE: Open Blog Revolution Demo Test
URL: https://admirable-monstera-29a236.netlify.app/
BASE: /
DESCRIPTION: Free blog template for nerds!!!!
LANG: EN
STYLE: serif-and-sans
AUTHOR: Iko
CONTACT: true
EMAIL: youremail@email.com
POST_COVER: true
POST_THUMBNAILS: true
POST_SUGGESTIONS: true
HOME_NB_POSTS: 6
MENU:
  - label: RSS
    url: rss.xml
  - label: Archive
    url: archive
BLOG_COVER:
  src: obr_large.png
  alt: Open Blog Revolution
